import { Event } from "./types";

export const mapApiItemToEvent = (item: any): Event => ({
  id: item.id,
  title: item.title,
  description: item.description,
  start_date: item.start_date,
  end_date: item.end_date,
  location: item.location,
  price: item.price,
  image_ids: item.image_ids,
  is_public: item.is_public,
  currency: item.currency,
  main_attractions: item.main_attractions,
  language: item.language,
  skill_level: item.skill_level,
  min_age: item.min_age,
  max_age: item.max_age,
  min_child_age: item.min_child_age,
  itinerary: item.itinerary,
  included_trips: item.included_trips,
  food_description: item.food_description,
  price_includes: item.price_includes,
  price_excludes: item.price_excludes,
  accommodation_description: item.accommodation_description,
  guest_welcome_description: item.guest_welcome_description,
  paid_attractions: item.paid_attractions,
  cancellation_policy: item.cancellation_policy,
  important_info: item.important_info,
  program: item.program,
});
